[package]
name = "prime_time"
version = "0.1.0"
edition = "2021"

[dependencies]
is_prime = "2.0.9"
serde = { version="1.0.147", features=["derive"] }
serde_json = { version="1.0", features = ["raw_value"] }
